controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        en: '' # don't prefix URLs for english
        pl: '/pl'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
